[FUG]
# IP address
ip = 10.205.40.250
# port number
port = 2101
# poll interval in seconds
poll_interval = 1

[TPS]
# enable/disable TPS2 interlock monitoring [true/false]
interlock_mon = true
# IP address
ip = localhost
# interlock monitor RC code
rc = 601
# poll interval in seconds
poll_interval = 1
